project:
  type: website
  output-dir: docs
  render:
  - "!x-*.qmd"
  - "01*.qmd"
  - "02*.qmd"
  - index.qmd
  # - "*.qmd"

website:
  title: "Prison Heat Analysis"
  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Cleaning"
        contents: "01-*qmd"
      - section: "Analysis"
        contents: "02-*qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap