project:
  type: website
  render:
  - "!x-*.qmd"
  - "!ignore/*.qmd"
  - "01*.qmd"
  - "02*.qmd"
  - index.qmd
  # - "*.qmd"

website:
  title: "Prison Heat Analysis"
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Cleaning"
        contents: "01-*qmd"
      - section: "Analysis"
        contents: "02-*qmd"
    tools:
    - icon: github
      href: https://github.com/utdata/tdcj-prison-heat
    - icon: question-circle
      href: https://journalism.utexas.edu/innovation/

  page-footer: "Media Innovation Group" 

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap