project:
  type: website
  render:
  - "!x-*.qmd"
  - "01-*.qmd"
  # - "*.qmd"

website:
  title: "Prison Heat Analysis"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - auto: "*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap